### ISSUE TITLE
First execution ends with traceback, subsequent executions run just fine

### ISSUE THREAD

**Issue by kloesing** [robgjansen/onionperf#1]
```
vagrant@vagrant:/vagrant$ ./onionperf --tgen=/vagrant/shadow/src/plugin/shadow-plugin-tgen/build/tgen 
2015-06-25 02:11:06 1435223466.818067 [onionperf] [INFO] Using 'tor' binary at /usr/bin/tor
2015-06-25 02:11:06 1435223466.819609 [onionperf] [INFO] Using 'tgen' binary at /vagrant/shadow/src/plugin/shadow-plugin-tgen/build/tgen
2015-06-25 02:11:06 1435223466.821230 [onionperf] [INFO] Starting tgen server...
2015-06-25 02:11:06 1435223466.822458 [onionperf] [INFO] Starting tor server...
2015-06-25 02:11:28 1435223488.737308 [onionperf] [INFO] Starting tor client...
2015-06-25 02:11:45 1435223505.617906 [onionperf] [INFO] Starting tor loggers...
2015-06-25 02:11:45 1435223505.620156 [onionperf] [INFO] Pausing for 30 seconds to publish hidden service descriptor...
2015-06-25 02:12:15 1435223535.650621 [onionperf] [INFO] Starting tgen client...
2015-06-25 02:12:15 1435223535.651478 [onionperf] [INFO] Log files for the client and server porcesses are located in /vagrant
2015-06-25 02:12:15 1435223535.652675 [onionperf] [INFO] Cleaning up child processes now...
2015-06-25 02:12:17 1435223537.660627 [onionperf] [INFO] Child processes terminated
2015-06-25 02:12:17 1435223537.665249 [onionperf] [INFO] Child process cleanup complete!
2015-06-25 02:12:17 1435223537.665699 [onionperf] [INFO] Exiting
Traceback (most recent call last):
  File "./onionperf", line 388, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./onionperf", line 110, in main
    op.run()
  File "./onionperf", line 155, in run
    logging.info("Heartbeat: {0} downloads have completed successfully".format(self.__get_download_count()))
  File "./onionperf", line 187, in __get_download_count
    with open(".onionperf/client/tgen/tgen.log", 'r') as fin:
IOError: [Errno 2] No such file or directory: '.onionperf/client/tgen/tgen.log'
```

My assumption is that that file is written shortly after `onionperf` expects it to exist.

**Comment by robgjansen** [comment]
Thanks for reporting @kloesing! Does the above commit fix this bug?

**Comment by kloesing** [comment]
It does.  Thanks!
