### ISSUE TITLE
Traceback when producing .tpf file

### ISSUE THREAD

**Issue by kloesing** [robgjansen/onionperf#18]
```
$ onionperf analyze --tgen ~/run/onionperf-data/tgen-client/onionperf.tgen.log --torctl ~/run/onionperf-data/tor-client/onionperf.torctl.log -t
2016-03-16 10:41:06 1458124866.543423 [onionperf] [INFO] parsing log file at /home/ubuntu/run/onionperf-data/tgen-client/onionperf.tgen.log
2016-03-16 10:41:06 1458124866.743521 [onionperf] [INFO] parsing log file at /home/ubuntu/run/onionperf-data/tor-client/onionperf.torctl.log
160 176
2016-03-16 10:41:10 1458124870.677777 [onionperf] [INFO] saving analysis results to /home/ubuntu/test/onionperf.analysis.json.xz
2016-03-16 10:41:12 1458124872.602096 [onionperf] [INFO] done!
2016-03-16 10:41:12 1458124872.602630 [onionperf] [INFO] saving analysis results to /home/ubuntu/test/ip-172-16-0-86-51200-2016-03-16.tpf.xz
{'last_byte': 0.727828, 'proxy_request': 0.00078, 'checksum': 0.727953, 'proxy_response': 0.179567, 'socket_connect': 0.000161, 'first_byte': 0.430547, 'proxy_init': 0.000204, 'command': 0.179648, 'proxy_choice': 0.000687, 'payload_progress': {0.0: 0.43041086196899414, 0.5: 0.5566728115081787, 0.4: 0.554987907409668, 0.8: 0.7180359363555908, 1.0: 0.7279529571533203, 0.1: 0.43041086196899414, 0.3: 0.4822959899902344, 0.6: 0.6364848613739014, 0.2: 0.47347283363342285, 0.9: 0.7196469306945801, 0.7: 0.6382029056549072}, 'response': 0.391301, 'socket_create': 9e-06}
{'last_byte': 0.957269, 'proxy_request': 0.000792, 'checksum': 0.957411, 'proxy_response': 0.301671, 'socket_connect': 0.000155, 'first_byte': 0.6422, 'proxy_init': 0.000198, 'command': 0.301736, 'proxy_choice': 0.000699, 'payload_progress': {0.0: 0.6420190334320068, 0.5: 0.755763053894043, 0.4: 0.7552042007446289, 0.8: 0.9045040607452393, 1.0: 0.9574110507965088, 0.1: 0.6420190334320068, 0.3: 0.7545981407165527, 0.6: 0.7615780830383301, 0.2: 0.6827092170715332, 0.9: 0.9054610729217529, 0.7: 0.8771240711212158}, 'response': 0.602979, 'socket_create': 9e-06}
{'last_byte': 1.408053, 'proxy_request': 0.000837, 'checksum': 1.408189, 'proxy_response': 0.410534, 'socket_connect': 0.00017, 'first_byte': 0.91325, 'proxy_init': 0.000213, 'command': 0.410607, 'proxy_choice': 0.000731, 'payload_progress': {0.0: 0.9130940437316895, 0.5: 1.102247953414917, 0.4: 1.063920021057129, 0.8: 1.2117180824279785, 1.0: 1.408189058303833, 0.1: 0.922875165939331, 0.3: 1.0104780197143555, 0.6: 1.185028076171875, 0.2: 0.9245650768280029, 0.9: 1.310528039932251, 0.7: 1.1860589981079102}, 'response': 0.81761, 'socket_create': 9e-06}
{'last_byte': 1.008355, 'proxy_request': 0.000745, 'checksum': 1.008492, 'proxy_response': 0.26041, 'socket_connect': 0.000154, 'first_byte': 0.642004, 'proxy_init': 0.000196, 'command': 0.260484, 'proxy_choice': 0.000656, 'payload_progress': {0.0: 0.641855001449585, 0.5: 0.8088200092315674, 0.4: 0.7797598838806152, 0.8: 0.8774838447570801, 1.0: 1.0084919929504395, 0.1: 0.6485989093780518, 0.3: 0.776033878326416, 0.6: 0.8739898204803467, 0.2: 0.686694860458374, 0.9: 0.9392130374908447, 0.7: 0.8739898204803467}, 'response': 0.64196, 'socket_create': 9e-06}
{'last_byte': 1.598095, 'proxy_request': 0.000808, 'checksum': 1.598229, 'proxy_response': 0.398845, 'socket_connect': 0.00017, 'first_byte': 0.835746, 'proxy_init': 0.000215, 'command': 0.39891, 'proxy_choice': 0.000717, 'payload_progress': {0.0: 0.8355889320373535, 0.5: 1.1602349281311035, 0.4: 1.1273140907287598, 0.8: 1.2698230743408203, 1.0: 1.598228931427002, 0.1: 0.8355889320373535, 0.3: 0.980633020401001, 0.6: 1.1625261306762695, 0.2: 0.8413970470428467, 0.9: 1.3796019554138184, 0.7: 1.1625261306762695}, 'response': 0.799344, 'socket_create': 9e-06}
{'last_byte': 1.047385, 'proxy_request': 0.000733, 'checksum': 1.047534, 'proxy_response': 0.321719, 'socket_connect': 0.000164, 'first_byte': 0.683479, 'proxy_init': 0.000206, 'command': 0.32178, 'proxy_choice': 0.000648, 'payload_progress': {0.0: 0.6832559108734131, 0.5: 0.8047139644622803, 0.4: 0.7945969104766846, 0.8: 0.94610595703125, 1.0: 1.0475339889526367, 0.1: 0.7028329372406006, 0.3: 0.792855978012085, 0.6: 0.837803840637207, 0.2: 0.7512240409851074, 0.9: 0.9545559883117676, 0.7: 0.8492250442504883}, 'response': 0.64676, 'socket_create': 1e-05}
{'payload_progress': {0.0: 0.1113278865814209}, 'proxy_request': 0.000926, 'proxy_response': 0.111466, 'socket_connect': 0.000197, 'first_byte': 0.233029, 'proxy_init': 0.00025, 'command': 0.111528, 'proxy_choice': 0.000717, 'response': 0.232986, 'socket_create': 1e-05}
Traceback (most recent call last):
  File "/usr/local/bin/onionperf", line 459, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "/usr/local/bin/onionperf", line 312, in main
    args.func(args)
  File "/usr/local/bin/onionperf", line 385, in analyze
    analysis.export_torperf_version_1_0(output_prefix=args.prefix, do_compress=True)
  File "/usr/local/lib/python2.7/dist-packages/onionperf/analysis.py", line 187, in export_torperf_version_1_0
    d['DATACOMPLETE'] = ts_to_str(xfer_db['unix_ts_start'] + xfer_db['elapsed_seconds']['last_byte'])
KeyError: 'last_byte'
```

This is ae3a739c83620747077a2a9ded582b72517b433c with an additional debug line:

```
diff --git a/onionperf/analysis.py b/onionperf/analysis.py
index 830d52d..aeb590c 100644
--- a/onionperf/analysis.py
+++ b/onionperf/analysis.py
@@ -183,6 +183,7 @@ class Analysis(object):
                         if xfer_db['elapsed_seconds']['payload_progress'][decile] is not None:
                             d['DATAPERC{0}'.format(int(decile * 100))] = ts_to_str(xfer_db['unix_ts_start'] + xfer_db['elapsed_seconds']['payload_progress'][decile])

+                    print xfer_db['elapsed_seconds']
                     d['DATACOMPLETE'] = ts_to_str(xfer_db['unix_ts_start'] + xfer_db['elapsed_seconds']['last_byte'])
                     # could be ioerror or timeout or etc, but i dont think torperf distinguishes these
                     d['DIDTIMEOUT'] = 1 if xfer_db['is_error'] is True else 0
```

I'm unsure what the right fix is here, because I don't know the reason why the `last_byte` field would be missing there.  Maybe we can just skip that line then, but I'm not sure.

**Comment by robgjansen** [comment]
Thanks for reporting! Would you be able to post your `onionperf.tgen.log` and `onionperf.torctl.log` somewhere where I could download them?

**Comment by kloesing** [comment]
Sure: https://people.torproject.org/~karsten/volatile/test2.tar.bz2

**Comment by robgjansen** [comment]
I think the above fix (in d22f2a8c03c7cf59f82192f95a2154027d4f6170) should fix the key errors.

**Comment by robgjansen** [comment]
@kloesing 
I noticed that some of the 'HOSTNAMEREMOTE' keys in your data contained 'HTTP'; that is not correct. I _think_ this is because you are using an old version of TGen that does not do some basic authentication with itself, and so the server is being connected to by a non-tgen client that thinks it is a regular HTTP server.

You can check if you are running the correct TGen by making sure you have a version that has this at the top:
https://github.com/shadow/shadow/blob/master/src/plugin/shadow-plugin-tgen/shd-tgen-transfer.c#L14

If I am wrong and you already have the latest TGen, then we may have another bug lurking.

**Comment by kloesing** [comment]
The fix seems to work, I'm now running OnionPerf using a clean data directory.  I'll let you know how that works in a few days.

Regarding the TGen version, I think I was running the latest version.  I re-ran `cmake` and `make` just in case I forgot to do that last time, but I think nothing has changed.  How about I send you the log files in a few days and you take a look if the problem persists?  Let me know if I should try out something else.

**Comment by robgjansen** [comment]
OK, great! I'm closing this ticket as fixed for now.

I also restarted my OnionPerf instance and can check it in a few days about the 'HTTP' thing. If there is a problem, we can open a new bug for that.
