### ISSUE TITLE
socket connection failed

### ISSUE THREAD

**Issue by myt0722** [robgjansen/onionperf#38]
Hi，
  I encountered socket connection failed while testing the onion network. So why is this happening?

> 2018-07-16 21:39:19 1531748359.490587 [onionperf] [INFO] Using 'tor' binary at /root/shadow-plugin-tor/build/tor/src/or/tor
2018-07-16 21:39:19 1531748359.490765 [onionperf] [INFO] Using 'tgen' binary at /root/shadow/src/plugin/shadow-plugin-tgen/build/tgen
2018-07-16 21:39:19 1531748359.490812 [onionperf] [INFO] Using 'twistd' binary at /usr/bin/twistd
2018-07-16 21:39:30 1531748370.719282 [onionperf] [INFO] Bootstrapping started...
2018-07-16 21:39:30 1531748370.719409 [onionperf] [INFO] Log files for the client and server processes will be placed in /newdisk/onionperf/onionperf/onionperf-data
2018-07-16 21:39:30 1531748370.719454 [onionperf] [INFO] Starting TGen server process on port 8080...
2018-07-16 21:39:30 1531748370.720069 [onionperf] [INFO] TGen server running at 0.0.0.0:8080
2018-07-16 21:39:30 1531748370.720134 [onionperf] [INFO] Logging TGen server process output to /newdisk/onionperf/onionperf/onionperf-data/tgen-server/onionperf.tgen.log
2018-07-16 21:39:30 1531748370.720445 [onionperf] [INFO] Starting Tor server process with ControlPort=13505, SocksPort=20558...
2018-07-16 21:39:30 1531748370.720523 [onionperf] [INFO] Logging Tor server process output to /newdisk/onionperf/onionperf/onionperf-data/tor-server/onionperf.tor.log
2018-07-16 21:40:40 1531748440.430948 [onionperf] [INFO] Logging Tor server control port monitor output to /newdisk/onionperf/onionperf/onionperf-data/tor-server/onionperf.torctl.log
2018-07-16 21:40:43 1531748443.438111 [onionperf] [INFO] Creating ephemeral hidden service...
2018-07-16 21:41:25 1531748485.461941 [onionperf] [INFO] Cleaning up child processes now...
2018-07-16 21:41:25 1531748485.462292 [onionperf] [INFO] Joining tgen_server_watchdog thread...
Exception in thread torctl_server_helper:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/onionperf/monitor.py", line 84, in tor_monitor_run
    torctl_monitor.run(newnym_interval_seconds=newnym_interval_seconds, done_ev=done_ev)
  File "/usr/lib/python2.7/site-packages/onionperf/monitor.py", line 27, in run
    torctl.authenticate()
  File "/usr/lib/python2.7/site-packages/stem/control.py", line 991, in authenticate
    stem.connection.authenticate(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/stem/connection.py", line 520, in authenticate
    raise AuthenticationFailure('socket connection failed (%s)' % exc)
AuthenticationFailure: socket connection failed (Received empty socket content.)
2018-07-16 21:41:25 1531748485.978180 [onionperf] [INFO] Joining tor_server_watchdog thread...
2018-07-16 21:41:26 1531748486.066931 [onionperf] [INFO] Joining torctl_server_helper thread...
2018-07-16 21:41:27 1531748487.070911 [onionperf] [INFO] Child processes terminated
2018-07-16 21:41:27 1531748487.071276 [onionperf] [INFO] Child process cleanup complete!
2018-07-16 21:41:27 1531748487.071451 [onionperf] [INFO] Exiting
Traceback (most recent call last):
  File "./onionperf", line 504, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./onionperf", line 330, in main
    args.func(args)
  File "./onionperf", line 383, in measure
    server_tgen_listen_port=server_tgen_port, server_tor_ctl_port=server_tor_ctl_port, server_tor_socks_port=server_tor_socks_port, twistd_port=twistd_port)
  File "/usr/lib/python2.7/site-packages/onionperf/measurement.py", line 214, in run
    tor_writable, torctl_writable = self.__start_tor_server(server_tor_ctl_port, server_tor_socks_port, {client_tgen_connect_port:server_tgen_listen_port})
  File "/usr/lib/python2.7/site-packages/onionperf/measurement.py", line 348, in __start_tor_server
    return self.__start_tor("server", control_port, socks_port, hs_port_mapping)
  File "/usr/lib/python2.7/site-packages/onionperf/measurement.py", line 395, in __start_tor
    torctl.authenticate()
  File "/usr/lib/python2.7/site-packages/stem/control.py", line 991, in authenticate
    stem.connection.authenticate(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/stem/connection.py", line 520, in authenticate
    raise AuthenticationFailure('socket connection failed (%s)' % exc)
stem.connection.AuthenticationFailure: socket connection failed (Received empty socket content.)

**Comment by irl** [comment]
This issue is almost 6 months old with no follow up, perhaps it is just noise at this point?

**Comment by robgjansen** [comment]
Sorry for the lack of attention. I'll close since it's been so long, but please re-open if you are still experiencing this issue!
